version: '3'
services:
  database:
    container_name: postgres_integrations
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres/1-data.sql:/docker-entrypoint-initdb.d/1-data.sql