server:
  port: 8091

spring:
  application:
    name: integrations
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/integrations
    username: postgres
    password: postgres

flyway:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/integrations
  schemas: public
  username: postgres
  password: postgres
aws:
  region: us-east-1
  access-key:  ${AWS_KEY}
  secret-key: ${AWS_SECRET_KEY}   
queue:
  employee:
    created:
      name: EMPLOYEE_CREATED_QUEUE
      pool-size: 1-3
    removed:
      name: EMPLOYEE_REMOVED_QUEUE
      pool-size: 1-3
environment:
  topics-config:
    - bean-name: employeeCreated
      topic-name: EMPLOYEE_CREATED_TOPIC
    - bean-name: employeeRemoved
      topic-name: EMPLOYEE_REMOVED_TOPIC
