server:
  port: 8091

aws:
 # sns:
 #   url: arn:aws:sns:us-east-1:952790931786:CREATED_TOPIC
  #sqs:
  #  url: arn:aws:sns:us-east-1:952790931786:CREATED_TOPIC
  region: us-east-1
  access-key:  ${AWS_KEY}
  secret-key: ${AWS_SECRET_KEY}   
queue:
  user:
    created:
      name: CREATED_QUEUE
      pool-size: 1-3
environment:
  topics-config:
    - bean-name: topicCreated
      topic-name: CREATED_TOPIC
