server:
  port: 8091

spring:
  application:
    name: integrations
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/integrations
      username: postgres
      password: postgres

flyway:
  url: jdbc:postgresql://localhost:5432/integrations
  schemas: public
  username: postgres
  password: postgres
aws:
  region: us-east-1
  access-key:  ${AWS_KEY}
  secret-key: ${AWS_SECRET_KEY}   
queue:
  user:
    created:
      name: CREATED_QUEUE
      pool-size: 1-3
environment:
  topics-config:
    - bean-name: topicCreated
      topic-name: CREATED_TOPIC
